sudo: false

language: python

cache:
  directories:
    - stripe-mock
  pip: false

env:
  global:
    - STRIPE_MOCK_VERSION=0.9.0

before_install:
  # Unpack and start stripe-mock so that the test suite can talk to it
  - |
    if [ ! -d "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}" ]; then
      mkdir -p stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/
      curl -L "https://github.com/stripe/stripe-mock/releases/download/v${STRIPE_MOCK_VERSION}/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -o "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz"
      tar -zxf "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}_linux_amd64.tar.gz" -C "stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/"
    fi
  - |
    stripe-mock/stripe-mock_${STRIPE_MOCK_VERSION}/stripe-mock > /dev/null &
    STRIPE_MOCK_PID=$!

install:
  - make init

script:
  - make ci

stages:
  - test
  - lint
  - coverage

jobs:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7-dev"
    - python: "pypy"
    - python: "pypy3"
    - stage: lint
      python: "2.7"
      script:
        - make lint
    - stage: coverage
      python: "2.7"
      python: "3.6"
      script:
        - make coverage
      after_success:
        - pipenv run coveralls
